travis:
  secure:
    BINSTAR_TOKEN: RxtqAYfGR9b8dRLpE2Nvrp2h2EZZBk6WhE8cfD8JOFUC3chDa6AeAd+usSK/VmMmGydf/r7TDvAU8lzqL50WvvjSBY6F09ybe3nfTDWp4LFzk61jedFGUZgUCs+hmuUZDWB/HlbVvOYflh4oPrAoMgda6O+8dmJFSy6ptB51fwXrAY9IVn4hcvTSptoC7YQfnTxYdyo3qfBZhUegKjYn63dgzvieHlC05zswILGS/HAIzEa3lD74Qw0y3NZkqNK3IpwEW0MpeiysXhuuWZ9ntIdqHlN78nmLws+n0rtbXuVq51ijxA2O0UGsN/Walb8fNKkcRmI2O9Mf0crruLAaLkPwur8ACbAmszu2eymZMsa7s3qcXdNFltZ4zRbP/MfltoUoiUexfBJhJbjI6ZSXvnmqMd4ElbIboD7jcbLSapElaZKZJb4e/QvSBC3aDLbIGc6hJkIkWcsNY4NDUKkPje478AgrZzL3JTHYjr7j37HbFYTYpUF75lQHzHxcE9m3BeRR9ws2sAazX8nL+U+G7FvInQ5iC+d3UYCVf7o7NdvbbnFV9nMc/UD2gDTcPwcyCR9IpjHzHK3CiawWS8gczYw086dwaupkeCuwVVg/cZIgczOWNaLtbu/m0Pbke37umepHoW368i3nDFYvQEMl+OWM1+RN6wgPQ1UF0EMC8pY=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
