travis:
  secure:
    BINSTAR_TOKEN: sCujPZc/DgJxC43GDOinoPZX209ZkIiYIGqkrHsIxB/up/tC87XXmTTACsAcj7y2lDWW2RNVs1qE1Tm7WTX0ZQBXP2l8r+RMRY2TsHPds7CfCXtKdivQQG8dT/wrrip9Qzg5H/n+zX0juAu4ut4DwKaM+T3BvaGM2YYy/koPHPtXxUkcl2QgPMeusVsgeDsoZb2/6MrYw4hj+EsqvKJUGebhTt9vJqW6kV1+9AQYLv9PUW6ZXU2NzbVjsPAMFPkQchF/ADK0/BGMnzFPbSgIBr3xzAwHyl2pLlOdQgByQmsPMicEfm2BHEyenCd0RGTrJWase7lkztcrQGfLF9uvE9QSnYH1AAtlREMpmH1NXPse7xEjGzj9SL7UK+S/Eno61eLWxIZ2XOx/DRwR7dSkKBGjnYRoZUHlfobce2N8LqB2lLBlPWMs3SV6b8B8dhjJ7FYI8Axy8lIqprg8L9nmbX5nP/IMbto6DlZv8DhJZBe56v5OfloeP7m803TSlsaUL7oiNZla6cMX6FCFUW9qXGe0WquVKTCk14RaMIpMFFJlVYvzsV6R8Hi+4g80V8Vw07jqo3Ih5CaNqz8R8q+cvV903YXwG6aNEQk0m2zS6uvuXo8CJC6K5u3KetE1UWFpt8mSsV15KzWISmFS3JTuYgp2NuvhyfGTrI1/VQPf/zg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
